// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr-wAgfpp0uMXwFxGHRtTH_FjnomchDjs',
    appId: '1:691821521227:web:a2161e67e34557a97b20ce',
    messagingSenderId: '691821521227',
    projectId: 'finger-chooser-app',
    authDomain: 'finger-chooser-app.firebaseapp.com',
    storageBucket: 'finger-chooser-app.firebasestorage.app',
    measurementId: 'G-Q5JGRRWRQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdGmG7lr3nDxBqRY6kgFuW-ZKvMLwOips',
    appId: '1:691821521227:android:ac92a94c7155a8aa7b20ce',
    messagingSenderId: '691821521227',
    projectId: 'finger-chooser-app',
    storageBucket: 'finger-chooser-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMAaWyhARAAyAUwgN4eO8KU87TV9dG_8',
    appId: '1:691821521227:ios:dd3111a84a191fd37b20ce',
    messagingSenderId: '691821521227',
    projectId: 'finger-chooser-app',
    storageBucket: 'finger-chooser-app.firebasestorage.app',
    iosBundleId: 'com.example.fingerChooserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTMAaWyhARAAyAUwgN4eO8KU87TV9dG_8',
    appId: '1:691821521227:ios:dd3111a84a191fd37b20ce',
    messagingSenderId: '691821521227',
    projectId: 'finger-chooser-app',
    storageBucket: 'finger-chooser-app.firebasestorage.app',
    iosBundleId: 'com.example.fingerChooserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr-wAgfpp0uMXwFxGHRtTH_FjnomchDjs',
    appId: '1:691821521227:web:526ba0e062dea9967b20ce',
    messagingSenderId: '691821521227',
    projectId: 'finger-chooser-app',
    authDomain: 'finger-chooser-app.firebaseapp.com',
    storageBucket: 'finger-chooser-app.firebasestorage.app',
    measurementId: 'G-6ES7DW7GGG',
  );
}
